### ISSUE TITLE
Use links with start time

### ISSUE THREAD

**Issue by rgponce** [andygruber/songseeker#17]
https://songseeker.grub3r.io/ does not accept the use of the "&t=" prefix in YouTube links

**Comment by weidi** [comment]
Probably fixed with #16 but thats waiting to be merged.

**Comment by andygruber** [comment]
Unfortunately the original author did not fix the issues, I did it now myself. Change is also already online.
